# Generated by Django 4.1.10 on 2023-08-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
